# Generated by Django 5.1.2 on 2024-10-10 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=250)),
                ('published_date', models.DateField()),
                ('publisher', models.CharField(max_length=250)),
                ('rental_fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('debt', models.IntegerField(verbose_name=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_datetime', models.DateTimeField()),
                ('returned_datetime', models.DateTimeField(blank=True)),
                ('overdue_fee', models.IntegerField(blank=True, verbose_name=[django.core.validators.MinValueValidator(0)])),
                ('fee_paid', models.IntegerField(blank=True, verbose_name=[django.core.validators.MinValueValidator(0)])),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_api.book')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_api.member')),
            ],
        ),
    ]
