# Generated by Django 5.1.2 on 2024-10-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_api.book'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_api.member'),
        ),
    ]
