# Generated by Django 5.1.2 on 2024-10-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0003_alter_member_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='debt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
