# Generated by Django 5.1.2 on 2024-10-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_alter_member_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_paid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='overdue_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
